import type { Metadata } from "next";
import { ExternalLink } from "@/components/ExternalLink";
import { PageHero } from "@/components/PageHero";
import { siteConfig } from "@/lib/content";

export const metadata: Metadata = { title: "Escolas e parceiros", description: "Leve o Programa Pitagóricos à sua escola, município ou rede de ensino." };

export default function PartnersPage() {
  return <main id="conteudo"><PageHero eyebrow="Para escolas, secretarias e instituições" title="Um programa para encontrar talentos e ampliar horizontes." description="Formação olímpica, pesquisa, carreira, liderança e inovação em uma implementação gradual e mensurável."><ExternalLink className="button button-yellow" href={siteConfig.partnerFormUrl} eventName="partner_contact_click">Conversar sobre parceria</ExternalLink></PageHero>
    <section className="section"><div className="shell"><div className="section-heading"><p className="eyebrow">O programa</p><h2>Da curiosidade ao protagonismo.</h2><p>Uma atuação complementar ao currículo escolar, feita para gerar oportunidade sem exigir uma transformação estrutural imediata.</p></div><div className="program-grid"><article><span>01</span><h2>Diagnóstico</h2><p>Mapeamento do contexto, das olimpíadas prioritárias e dos estudantes interessados.</p></article><article><span>02</span><h2>Formação</h2><p>Trilhas, aulas, simulados e materiais preparados por medalhistas.</p></article><article><span>03</span><h2>Acompanhamento</h2><p>Comunidade, orientação de estudos e desenvolvimento de lideranças.</p></article><article><span>04</span><h2>Impacto</h2><p>Indicadores quantitativos e qualitativos para evolução e prestação de contas.</p></article></div></div></section>
    <section className="section section-soft"><div className="shell case-grid"><div><p className="eyebrow">Caso em destaque</p><h2>Inesp: conteúdo de alto padrão com alcance potencial de 700 mil estudantes.</h2><p>A parceria viabilizou a coedição de e-books impressos e o lançamento de <em>Questões Comentadas de Olimpíadas Científicas</em> na Feira de Ciências e Tecnologia do Ceará.</p></div><div className="case-stat"><strong>700 mil</strong><span>estudantes cearenses</span><small>alcance potencial informado para a parceria</small></div></div></section>
    <section className="dark-section"><div className="shell pilot-grid"><div><p className="eyebrow light">Plano piloto presencial</p><h2>Domingos Mourão, Piauí.</h2><p>O município é o ponto de partida previsto para núcleos presenciais em estados com menor participação olímpica.</p></div><div><strong>1.132</strong><span>matrículas na educação básica</span><small>Contexto do município; não representa impacto já realizado pelo projeto.</small></div></div></section>
    <section className="section"><div className="shell resource-use"><div><p className="eyebrow">Onde o apoio gera impacto</p><h2>Estrutura para crescer com qualidade.</h2></div><ul><li>Formalização institucional e governança</li><li>Bolsas para membros de baixa renda</li><li>Impressão e distribuição de materiais</li><li>Desenvolvimento da plataforma EAD</li><li>Logística para expansão territorial</li><li>Equipamentos e produção audiovisual</li></ul></div></section>
    <section className="final-cta"><div className="shell final-cta-inner"><div><p className="eyebrow light">Vamos construir a próxima oportunidade?</p><h2>Leve o Pitagóricos à sua rede.</h2></div><div>{siteConfig.partnerFormUrl ? <ExternalLink className="button button-yellow" href={siteConfig.partnerFormUrl} eventName="partner_contact_click">Iniciar conversa</ExternalLink> : <p className="cta-pending">O formulário institucional será ativado antes do lançamento.</p>}</div></div></section>
  </main>;
}
