import type { Metadata } from "next";
import { ExternalLink } from "@/components/ExternalLink";
import { PageHero } from "@/components/PageHero";
import { siteConfig } from "@/lib/content";

export const metadata: Metadata = { title: "Escolas e parceiros", description: "Leve o Programa Pitagóricos à sua escola, município ou rede de ensino." };

export default function PartnersPage() {
  return <main id="conteudo"><PageHero eyebrow="Para escolas, secretarias e instituições" title="Leve a preparação olímpica para a sua rede." description="O programa pode começar com uma olimpíada ou um grupo de estudantes e crescer conforme a realidade da instituição."><ExternalLink className="button button-yellow" href={siteConfig.partnerFormUrl} eventName="partner_contact_click">Conversar sobre parceria</ExternalLink></PageHero>
    <section className="section"><div className="shell"><div className="section-heading"><p className="eyebrow">Como funciona</p><h2>Uma implementação por etapas.</h2><p>O trabalho complementa as aulas e é ajustado às olimpíadas, à equipe e ao número de estudantes de cada instituição.</p></div><div className="program-grid"><article><span>01</span><h2>Contexto</h2><p>Levantamento das olimpíadas prioritárias e dos estudantes interessados.</p></article><article><span>02</span><h2>Preparação</h2><p>Trilhas, aulas, simulados e materiais feitos por medalhistas.</p></article><article><span>03</span><h2>Acompanhamento</h2><p>Orientação de estudos e um canal para dúvidas e avisos.</p></article><article><span>04</span><h2>Avaliação</h2><p>Acompanhamento da participação e dos resultados do programa.</p></article></div></div></section>
    <section className="section section-soft"><div className="shell case-grid"><div><p className="eyebrow">Parceria com o Inesp</p><h2>Publicação de materiais com alcance potencial de 700 mil estudantes.</h2><p>A parceria viabilizou a coedição de e-books impressos e o lançamento de <em>Questões Comentadas de Olimpíadas Científicas</em> na Feira de Ciências e Tecnologia do Ceará.</p></div><div className="case-stat"><strong>700 mil</strong><span>estudantes cearenses</span><small>alcance potencial informado para a parceria</small></div></div></section>
    <section className="dark-section"><div className="shell pilot-grid"><div><p className="eyebrow light">Plano piloto presencial</p><h2>Domingos Mourão, Piauí.</h2><p>O município é o ponto de partida previsto para núcleos presenciais em estados com menor participação olímpica.</p></div><div><strong>1.132</strong><span>matrículas na educação básica</span><small>Contexto do município; não representa impacto já realizado pelo projeto.</small></div></div></section>
    <section className="section"><div className="shell resource-use"><div><p className="eyebrow">Formas de apoio</p><h2>O que uma parceria pode viabilizar.</h2></div><ul><li>Bolsas para membros de baixa renda</li><li>Impressão e distribuição de materiais</li><li>Logística para atividades presenciais</li><li>Equipamentos e produção audiovisual</li></ul></div></section>
    <section className="final-cta"><div className="shell final-cta-inner"><div><p className="eyebrow light">Contato institucional</p><h2>Converse com a equipe do projeto.</h2></div><div>{siteConfig.partnerFormUrl ? <ExternalLink className="button button-yellow" href={siteConfig.partnerFormUrl} eventName="partner_contact_click">Iniciar conversa</ExternalLink> : <p className="cta-pending">O formulário institucional será adicionado assim que a equipe enviar o endereço.</p>}</div></div></section>
  </main>;
}
