"use client";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import type { Material } from "@/lib/database.types";
import { getSupabaseBrowserClient } from "@/lib/supabase";
import { useAuth } from "./AuthProvider";
const all = "Todos";
const labels: Record<string, string> = { aprender: "Aprender", praticar: "Praticar", revisar: "Revisar", simular: "Simular" };
export function MaterialCatalog() {
  const params = useSearchParams(); const { user } = useAuth(); const client = getSupabaseBrowserClient();
  const [materials, setMaterials] = useState<Material[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [subject, setSubject] = useState(params.get("materia") || all); const [olympiad, setOlympiad] = useState(params.get("olimpiada") || all); const [level, setLevel] = useState(all); const [objective, setObjective] = useState(all); const [type, setType] = useState(all);
  const [favorites, setFavorites] = useState<string[]>([]); const [completed, setCompleted] = useState<string[]>([]);
  useEffect(() => { const timer = window.setTimeout(() => { if (!client) { setLoading(false); return; } (async () => { const { data, error: loadError } = await client.from("materials").select("*").eq("status", "published").order("sort_order").order("title"); if (loadError) setError("Não foi possível carregar os materiais agora."); else setMaterials(data ?? []); setLoading(false); })(); }, 0); return () => window.clearTimeout(timer); }, [client]);
  useEffect(() => { const timer = window.setTimeout(() => { if (!client || !user) { setFavorites([]); setCompleted([]); return; } Promise.all([client.from("favorites").select("material_id"), client.from("material_progress").select("material_id")]).then(([fav, progress]) => { setFavorites((fav.data ?? []).map((item) => item.material_id)); setCompleted((progress.data ?? []).map((item) => item.material_id)); }); }, 0); return () => window.clearTimeout(timer); }, [client, user]);
  const subjects = useMemo(() => Array.from(new Set(materials.map((item) => item.subject))).sort(), [materials]);
  const options = (key: "olympiad" | "material_type" | "objective") => [all, ...Array.from(new Set(materials.map((item) => item[key]).filter(Boolean) as string[])).sort()];
  const levels = [all, ...Array.from(new Set(materials.flatMap((item) => item.levels))).sort()];
  const filtered = useMemo(() => materials.filter((item) => (subject === all || item.subject === subject) && (olympiad === all || item.olympiad === olympiad) && (level === all || item.levels.includes(level)) && (objective === all || item.objective === objective) && (type === all || item.material_type === type)), [materials, subject, olympiad, level, objective, type]);
  async function toggleFavorite(id: string) { if (!client || !user) return window.location.assign("/entrar?redirect=/materiais"); if (favorites.includes(id)) { await client.from("favorites").delete().eq("material_id", id); setFavorites((v) => v.filter((item) => item !== id)); } else { const { error: mutationError } = await client.from("favorites").insert({ user_id: user.id, material_id: id, created_at: new Date().toISOString() }); if (!mutationError) setFavorites((v) => [...v, id]); } }
  async function toggleComplete(id: string) { if (!client || !user) return window.location.assign("/entrar?redirect=/materiais"); if (completed.includes(id)) { await client.from("material_progress").delete().eq("material_id", id); setCompleted((v) => v.filter((item) => item !== id)); } else { const { error: mutationError } = await client.from("material_progress").insert({ user_id: user.id, material_id: id, completed_at: new Date().toISOString() }); if (!mutationError) setCompleted((v) => [...v, id]); } }
  async function openMaterial(material: Material) { if (material.source_kind === "external" && material.external_url) { try { const url = new URL(material.external_url); if (!['http:', 'https:'].includes(url.protocol)) throw new Error(); return window.open(url.href, "_blank", "noopener,noreferrer"); } catch { setError("Este material tem um link inválido."); return; } } if (!client) return; const { data, error: invokeError } = await client.functions.invoke("material-file", { body: { materialId: material.id } }); if (invokeError || !data?.signedUrl) setError("Não foi possível abrir este arquivo agora."); else window.open(data.signedUrl, "_blank", "noopener,noreferrer"); }
  return <>
    {subjects.length > 0 && <nav className="subject-tabs" aria-label="Matérias disponíveis"><button className={subject === all ? "active" : ""} onClick={() => setSubject(all)}>Todas</button>{subjects.map((item) => <button className={subject === item ? "active" : ""} key={item} onClick={() => setSubject(item)}>{item}</button>)}</nav>}
    <div className="filters" aria-label="Filtros de materiais"><label>Matéria<select value={subject} onChange={(e) => setSubject(e.target.value)}><option>{all}</option>{subjects.map((item) => <option key={item}>{item}</option>)}</select></label><label>Olimpíada<select value={olympiad} onChange={(e) => setOlympiad(e.target.value)}>{options("olympiad").map((item) => <option key={item}>{item}</option>)}</select></label><label>Nível<select value={level} onChange={(e) => setLevel(e.target.value)}>{levels.map((item) => <option key={item}>{item}</option>)}</select></label><label>Objetivo<select value={objective} onChange={(e) => setObjective(e.target.value)}>{options("objective").map((item) => <option key={item} value={item}>{labels[item] ?? item}</option>)}</select></label><label>Tipo<select value={type} onChange={(e) => setType(e.target.value)}>{options("material_type").map((item) => <option key={item}>{item}</option>)}</select></label><button className="clear-filters" onClick={() => { setSubject(all); setOlympiad(all); setLevel(all); setObjective(all); setType(all); }}>Limpar</button></div>
    {error && <p className="form-message" role="alert">{error}</p>}{loading ? <p className="loading-state">Carregando materiais…</p> : <p className="result-count" aria-live="polite">{filtered.length} {filtered.length === 1 ? "material encontrado" : "materiais encontrados"}</p>}
    {!loading && filtered.length === 0 ? <div className="state-card"><h2>Nenhum material publicado aqui ainda.</h2><p>O catálogo mostra somente conteúdos revisados e publicados pela equipe.</p></div> : <div className="material-grid">{filtered.map((item) => <article className="material-card" key={item.id}><div className="material-meta"><span>{item.subject}</span>{item.olympiad && <span>{item.olympiad}</span>}<span>{labels[item.objective] ?? item.objective}</span></div><h2>{item.title}</h2><p>{item.description}</p><p className="material-level">{item.levels.join(" · ")} · {item.material_type}</p><div className="material-actions"><button className="button button-yellow compact" onClick={() => openMaterial(item)}>Abrir material</button><button className="button button-outline-light compact" aria-pressed={favorites.includes(item.id)} onClick={() => toggleFavorite(item.id)}>{favorites.includes(item.id) ? "Remover favorito" : "Favoritar"}</button><button className="text-button" aria-pressed={completed.includes(item.id)} onClick={() => toggleComplete(item.id)}>{completed.includes(item.id) ? "Desfazer conclusão" : "Marcar como concluído"}</button></div></article>)}</div>}
  </>;
}
