"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useAuth } from "./AuthProvider";
import { getSupabaseBrowserClient } from "@/lib/supabase";
import type { Goal, Material, StudentPreferences } from "@/lib/database.types";
import { grades } from "@/lib/olympiad-levels";
import { recommend } from "@/lib/recommendations";
const subjectOptions = ["Matemática", "Física", "Astronomia", "Química", "Biologia", "História", "Interdisciplinar"];
const olympiadOptions = ["OBA", "OBMEP", "ONC", "Ainda não sei"];
const emptyPreferences: Omit<StudentPreferences, "user_id" | "updated_at"> = { grade: "", subjects: [], olympiads: [], objective: "começar", experience: "nunca participei", onboarding_completed: false };
function MultiChoice({ legend, options, value, onChange }: { legend: string; options: string[]; value: string[]; onChange: (value: string[]) => void }) { return <fieldset><legend>{legend}</legend><div className="choice-grid">{options.map((item) => <label className={value.includes(item) ? "selected" : ""} key={item}><input type="checkbox" checked={value.includes(item)} onChange={() => onChange(value.includes(item) ? value.filter((v) => v !== item) : [...value, item])} />{item}</label>)}</div></fieldset>; }
export function StudentDashboard() {
  const { user } = useAuth(); const client = getSupabaseBrowserClient();
  const [prefs, setPrefs] = useState(emptyPreferences); const [loaded, setLoaded] = useState(false); const [editing, setEditing] = useState(false); const [materials, setMaterials] = useState<Material[]>([]); const [favorites, setFavorites] = useState<string[]>([]); const [completed, setCompleted] = useState<string[]>([]); const [goals, setGoals] = useState<Goal[]>([]); const [goalText, setGoalText] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { if (!client || !user) return; (async () => { const [pref, mats, fav, progress, goalRows] = await Promise.all([client.from("student_preferences").select("*").eq("user_id", user.id).maybeSingle(), client.from("materials").select("*").eq("status", "published").order("sort_order"), client.from("favorites").select("material_id"), client.from("material_progress").select("material_id"), client.from("goals").select("*").order("position").order("created_at")]); if (pref.data) setPrefs(pref.data); if (mats.data) setMaterials(mats.data); setFavorites((fav.data ?? []).map((i) => i.material_id)); setCompleted((progress.data ?? []).map((i) => i.material_id)); setGoals(goalRows.data ?? []); setLoaded(true); })(); }, [client, user]);
  const recommendation = useMemo(() => recommend({ grade: prefs.grade, subjects: prefs.subjects, olympiads: prefs.olympiads, objective: prefs.objective, experience: prefs.experience }, materials), [prefs, materials]);
  async function savePreferences(e: React.FormEvent) { e.preventDefault(); if (!client || !user || !prefs.grade || prefs.subjects.length === 0 || prefs.olympiads.length === 0) return setMessage("Preencha a série, ao menos uma matéria e uma olimpíada ou 'Ainda não sei'."); const payload = { ...prefs, user_id: user.id, onboarding_completed: true, updated_at: new Date().toISOString() }; const { error } = await client.from("student_preferences").upsert(payload); if (error) setMessage(error.message); else { setPrefs(payload); setEditing(false); setMessage("Preferências salvas."); } }
  async function toggleComplete(id: string) { if (!client || !user) return; if (completed.includes(id)) { await client.from("material_progress").delete().eq("material_id", id); setCompleted((v) => v.filter((i) => i !== id)); } else { await client.from("material_progress").insert({ user_id: user.id, material_id: id, completed_at: new Date().toISOString() }); setCompleted((v) => [...v, id]); } }
  async function removeFavorite(id: string) { if (!client) return; await client.from("favorites").delete().eq("material_id", id); setFavorites((v) => v.filter((i) => i !== id)); }
  async function addGoal(e: React.FormEvent) { e.preventDefault(); if (!client || !user || !goalText.trim()) return; const { data, error } = await client.from("goals").insert({ user_id: user.id, text: goalText.trim(), position: goals.length }).select("*").single(); if (!error && data) { setGoals((v) => [...v, data]); setGoalText(""); } }
  async function updateGoal(goal: Goal, updates: Partial<Goal>) { if (!client) return; const { data } = await client.from("goals").update(updates).eq("id", goal.id).select("*").single(); if (data) setGoals((v) => v.map((item) => item.id === goal.id ? data : item)); }
  async function editGoal(goal: Goal) { const text = window.prompt("Edite sua meta", goal.text)?.trim(); if (text) await updateGoal(goal, { text }); }
  async function deleteGoal(id: string) { if (!client || !window.confirm("Excluir esta meta?")) return; await client.from("goals").delete().eq("id", id); setGoals((v) => v.filter((i) => i.id !== id)); }
  if (!loaded) return <p className="loading-state">Carregando sua área…</p>;
  if (!prefs.onboarding_completed || editing) return <section className="dashboard-panel"><div className="section-heading"><p className="eyebrow">{editing ? "Preferências" : "Primeiro acesso"}</p><h1>{editing ? "Atualize seu perfil de estudos." : "Vamos personalizar sua área."}</h1><p>As respostas podem ser alteradas depois.</p></div><form className="onboarding-form" onSubmit={savePreferences}><label>1. Série<select required value={prefs.grade} onChange={(e) => setPrefs({ ...prefs, grade: e.target.value })}><option value="">Selecione</option>{grades.map((g) => <option value={g.value} key={g.value}>{g.label}</option>)}</select></label><MultiChoice legend="2. Matérias de interesse" options={subjectOptions} value={prefs.subjects} onChange={(subjects) => setPrefs({ ...prefs, subjects })} /><MultiChoice legend="3. Olimpíadas de interesse" options={olympiadOptions} value={prefs.olympiads} onChange={(olympiads) => setPrefs({ ...prefs, olympiads })} /><label>4. Objetivo atual<select value={prefs.objective} onChange={(e) => setPrefs({ ...prefs, objective: e.target.value })}><option value="começar">Começar</option><option value="estudar">Estudar</option><option value="praticar">Praticar</option><option value="prova próxima">Prova próxima</option></select></label><label>5. Experiência<select value={prefs.experience} onChange={(e) => setPrefs({ ...prefs, experience: e.target.value })}><option value="nunca participei">Nunca participei</option><option value="já participei">Já participei</option><option value="já fui premiado/medalhei">Já fui premiado/medalhei</option></select></label>{message && <p role="alert" className="form-message">{message}</p>}<div className="form-actions"><button className="button button-yellow">Salvar e continuar</button>{editing && <button type="button" className="button button-outline-light" onClick={() => setEditing(false)}>Cancelar</button>}</div></form></section>;
  const favoriteMaterials = materials.filter((m) => favorites.includes(m.id)); const percent = materials.length ? Math.round(completed.length / materials.length * 100) : 0;
  return <div className="dashboard-grid"><section className="dashboard-panel dashboard-wide"><p className="eyebrow">Próximo passo</p><h1>{recommendation.nextStep}</h1><p>Recomendação baseada na série, interesses, objetivo e experiência que você informou.</p></section><section className="dashboard-panel"><h2>Minhas olimpíadas</h2>{recommendation.olympiads.length ? recommendation.olympiads.map((item) => <article className="mini-card" key={item.name}><strong>{item.name} · {item.level}</strong><p>{item.reason}</p><Link href={`/olimpiadas/${item.slug}`}>Abrir página</Link></article>) : <p>Nenhuma recomendação disponível.</p>}</section><section className="dashboard-panel"><h2>Progresso</h2><strong className="progress-number">{percent}%</strong><p>{completed.length} de {materials.length} materiais publicados concluídos manualmente.</p></section><section className="dashboard-panel dashboard-wide"><h2>Recomendados para você</h2>{recommendation.materials.length ? <div className="mini-grid">{recommendation.materials.map((item) => <article className="mini-card" key={item.id}><small>{item.subject} · {item.olympiad}</small><h3>{item.title}</h3><p>{item.description}</p><button className="text-button" onClick={() => toggleComplete(item.id)}>{completed.includes(item.id) ? "Desfazer conclusão" : "Marcar como concluído"}</button></article>)}</div> : <p>Nenhum material publicado compatível ainda. <Link href="/materiais">Ver catálogo</Link></p>}</section><section className="dashboard-panel"><h2>Favoritos</h2>{favoriteMaterials.length ? favoriteMaterials.map((item) => <div className="goal-row" key={item.id}><span>{item.title}</span><button onClick={() => removeFavorite(item.id)}>Remover</button></div>) : <p>Seus materiais salvos aparecerão aqui.</p>}</section><section className="dashboard-panel"><h2>Metas</h2><form className="goal-form" onSubmit={addGoal}><label className="sr-only" htmlFor="new-goal">Nova meta</label><input id="new-goal" value={goalText} onChange={(e) => setGoalText(e.target.value)} placeholder="Ex.: Fazer simulado N2"/><button className="button button-yellow compact">Adicionar</button></form>{goals.map((goal) => <div className="goal-row" key={goal.id}><input aria-label={`Concluir ${goal.text}`} type="checkbox" checked={goal.completed} onChange={() => updateGoal(goal, { completed: !goal.completed })}/><span className={goal.completed ? "completed" : ""}>{goal.text}</span><button onClick={() => editGoal(goal)}>Editar</button><button onClick={() => deleteGoal(goal.id)}>Excluir</button></div>)}</section><section className="dashboard-panel dashboard-wide preferences-summary"><div><h2>Preferências</h2><p>{grades.find((g) => g.value === prefs.grade)?.label} · {prefs.subjects.join(", ")} · {prefs.olympiads.join(", ")}</p></div><button className="button button-outline-light" onClick={() => setEditing(true)}>Editar preferências</button></section></div>;
}
